#!/usr/bin/env python3

import sys
import csv

def ncut(column_names: list[str], infile):
    reader = csv.DictReader(infile, delimiter="\t")
    selected_fields = column_names.split(",")
        
    writer = csv.DictWriter(sys.stdout, fieldnames=selected_fields, delimiter='\t', extrasaction='ignore')
    writer.writeheader()

    for row in reader:
        print(row)
        writer.writerow(row)

if __name__ == "__main__":

    if len(sys.argv) < 2:
        print("Usage: ncut colnames [file]")
        sys.exit(1)
    
    column_names = sys.argv[1]

    if len(sys.argv) == 3:
        with open(sys.argv[2], 'r', newline='') as infile:
            ncut(column_names, infile)
    else:
        ncut(column_names, sys.stdin)

